dev_support/full_compilation/README.md, dev_support/full_compilation/pom.xml, gemoc_studio/plugins/org.eclipse.gemoc.language_workbench.documentation/pom.xml, gemoc_studio/pom.xml, gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.updatesite/category.xml
I've updated the dev_support/full_compilation script in order to make sure to be able to fully compile the studio locally in one command.
This is documented in the README.md file.
=> Local full build support

commons/plugins/org.eclipse.gemoc.commons.eclipse.messagingsystem.api/src/main/java/org/eclipse/gemoc/commons/eclipse/messagingsystem/api/MessagingSystemManager.java
based on [previous Erwan's PR](https://github.com/gemoc/gemoc-studio/pull/52)
Signed-off-by: ebousse <erwan.bousse@tuwien.ac.at>
=> Make more robust retry loop

commons/plugins/org.eclipse.gemoc.commons.eclipse.messagingsystem.ui/META-INF/MANIFEST.MF, commons/plugins/org.eclipse.gemoc.commons.eclipse.messagingsystem.ui/src/main/java/org/eclipse/gemoc/commons/eclipse/messagingsystem/ui/internal/console/EclipseConsoleIO.java
=> ensures to run changeStyle in an UI thread when printing large messages on console

Jenkinsfile, dev_support/jenkins/showGitBranches.sh
Show  in the jenkins log a summary of the branches that are actually checked out in the multibranch pipeline.
This helps to debug version related issues.
=> Show summary of checked out branches in multibranch pipeline

README.md
Updated information on main readme of the github repo
=> Contact information update

gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.product/src/main/filtered-resources/products/index.html
fixes  https://github.com/eclipse/gemoc-studio/issues/128
=> Correct css for nightly build download index page

commons/plugins/org.eclipse.gemoc.commons.eclipse/src/org/eclipse/gemoc/commons/eclipse/Activator.java
Small change about wrong error level in the activator
=> Fix error level in activator logger

docs/org.eclipse.gemoc.studio.doc/src/main/asciidoc/master.asciidoc, docs/org.eclipse.gemoc.studio.doc/src/main/asciidoc/userguide/headless_overview_headContent.asciidoc, docs/org.eclipse.gemoc.studio.doc/src/main/asciidoc/userguide/headless_run_model_headContent.asciidoc
- update link to download page
- added section about running a model
- added an example of running a model from K3FSM official example
=> Update headless documentation

gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.mwb/src/org/eclipse/gemoc/studio/tests/system/mwb/userstory/DebugOfficialExampleK3FSM_Test.xtend, gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.mwb/src/org/eclipse/gemoc/studio/tests/system/mwb/userstory/DeployOfficialExampleK3FSM_Test.xtend
This PR adds more time to SWTbot before failing
It also improves the debug logs
=> Increase swtbot test timeout

gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.updatesite/category.xml, pom.xml
=> Bump ALE version to 2019-06-24

commons/plugins/org.eclipse.gemoc.dsl.model/src/org/eclipse/gemoc/dsl/impl/DslImpl.java
Hello,
I have created a pull request to fix a bug in the method getEntry of the class DslImpl.
Valentin
=> Fix method getEntry of DslImpl

gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.updatesite/category.xml, gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.updatesite/gemoc_studio.product, pom.xml
Use http://timesquare.inria.fr/update_site/photon instead of http://www.i3s.unice.fr/~deantoni/photon
=> Change Timesquare updatesite

gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.headless/src/org/eclipse/gemoc/gemoc_studio/headless/runner/ALEInterpretedSequentialRunner.java, gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.headless/src/org/eclipse/gemoc/gemoc_studio/headless/runner/PlainK3SequentialRunner.java
Companion PR to https://github.com/eclipse/gemoc-studio-modeldebugging/pull/144
Contributes to https://github.com/eclipse/gemoc-studio-execution-ale/issues/29
=> Uses new generic Context and RunConfiguration classes from execution framework

docs/org.eclipse.gemoc.studio.doc/src/main/asciidoc/dev/DevelopingNewAddons.asciidoc
contributes to https://github.com/eclipse/gemoc-studio-modeldebugging/issues/151
=> Updated documentation about IEngineAddon interface

official_samples/K3FSM/language_workbench/org.eclipse.gemoc.example.k3fsm.xdsml/K3fsm.dsl, official_samples/MelangeK3FSM/language_workbench/org.eclipse.gemoc.example.melangek3fsm.xsfsm.xsfsm/XSFSM.dsl
Signed-off-by: Ronan Guéguen <gueguen.ronan1@gmail.com>
=> "metaprog" entry added to dsl files for the GEMOC Studio examples

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE/bug_pull_request_template.md, .github/PULL_REQUEST_TEMPLATE/bump_pull_request_template.md, .github/PULL_REQUEST_TEMPLATE/documentation_pull_request_template.md, .github/PULL_REQUEST_TEMPLATE/enhancement_pull_request_template.md, .github/PULL_REQUEST_TEMPLATE/releng_pull_request_template.md
Provides templates for github issues and pull request
This helps having more consistent contributions
- add a few markdown files in the `.github` folder at the root of the repo
=> Provide github issue templates

gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.branding.feature/feature.xml, gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.updatesite/category.xml
Add explicit features for the `gemoc-studio-execution-ale` and `gemoc-studio-execution-java` repositories
Adapts the update site and main product.
- https://github.com/eclipse/gemoc-studio-execution-java/pull/18
=> Explicit repository feature

gemoc_studio/pom.xml, pom.xml
Changes the update site of K3 in order to follow its releases
Contribute to https://github.com/eclipse/gemoc-studio/issues/223
- PR https://github.com/eclipse/gemoc-studio/pull/224
- PR https://github.com/eclipse/gemoc-studio-modeldebugging/pull/185
- PR https://github.com/eclipse/gemoc-studio-execution-java/pull/16
- PR https://github.com/eclipse/gemoc-studio-execution-ale/pull/47
- PR https://github.com/eclipse/gemoc-studio-execution-moccml/pull/51
=> Consolidation and automatic bump of K3 versions

gemoc_studio/pom.xml, gemoc_studio/tests/org.eclipse.gemoc.studio.tests.logging.config/.classpath, gemoc_studio/tests/org.eclipse.gemoc.studio.tests.logging.config/.project, gemoc_studio/tests/org.eclipse.gemoc.studio.tests.logging.config/.settings/org.eclipse.jdt.core.prefs, gemoc_studio/tests/org.eclipse.gemoc.studio.tests.logging.config/META-INF/MANIFEST.MF, gemoc_studio/tests/org.eclipse.gemoc.studio.tests.logging.config/build.properties, gemoc_studio/tests/org.eclipse.gemoc.studio.tests.logging.config/logback.xml, gemoc_studio/tests/org.eclipse.gemoc.studio.tests.logging.config/pom.xml, gemoc_studio/tests/org.eclipse.gemoc.studio.tests.logging.config/src/org/eclipse/gemoc/studio/tests/logging/config/Activator.java, gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.lwb/pom.xml, gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.mwb/pom.xml, gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.mwb/src/org/eclipse/gemoc/studio/tests/system/mwb/userstory/DebugOfficialExampleK3FSM_Test.xtend, gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.mwb/src/org/eclipse/gemoc/studio/tests/system/mwb/userstory/DeployOfficialExampleK3FSM_Test.xtend, gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.mwb/src/org/eclipse/gemoc/studio/tests/system/mwb/userstory/DeployOfficialExampleK3MelangeFSM_Test.xtend, gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.mwb/src/org/eclipse/gemoc/studio/tests/system/mwb/userstory/ModelingWorkbenchTestHelper.xtend
Improves several test suite timings in order to decrease issues
Refactors some code for clarification
Contribute to https://github.com/eclipse/gemoc-studio/issues/123 
- PR #
=> Improve test suites timings

official_samples/K3FSM/docs/K3FSM.asciidoc
Updates to the K3FSM tutorial. 
Updated instructions for the latest GEMOC Studio.
Corrected some typos.
=> K3FSM docs corrections

gemoc_studio/plugins/gemoc_studio-eclipse-bom/pom.xml, gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.lwb/src/org/eclipse/gemoc/studio/tests/system/lwb/userstory/CreateMelangeBasedSingleSequentialLanguageFromOfficialFSM_Test.xtend, gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.lwb/src/org/eclipse/gemoc/studio/tests/system/lwb/userstory/CreateSingleSequentialLanguageFromOfficialFSM_Test.xtend, gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.mwb/pom.xml
Increase the version of Melange to 2022-09-29
Also change some of the integration tests to force a rebuild action before trying to open dialogs (sirius, trace addon generation)
=> Bump to melange 2022-09-29

README.md, index.html
Simply update some of the channels available to get help about the projet
Now includes a chat-on-matrix badge
=> Update "getting help" info in readme

gemoc_studio/plugins/gemoc_studio-eclipse-bom/pom.xml, gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.targetplatform/README.md, gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.targetplatform/gemoc_studio.target, gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.targetplatform/gemoc_studio.tpd, gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.updatesite/gemoc_studio.product, gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.lwb/src/org/eclipse/gemoc/studio/tests/system/lwb/feature/GenerateLangRuntime4OfficialExampleMelangeK3FSM_Test.xtend, official_samples/K3FSM/language_workbench/org.eclipse.gemoc.example.k3fsm.k3dsa/src/org/eclipse/gemoc/example/k3fsm/k3dsa/k3fsmAspects.xtend, official_samples/K3FSM/modeling_workbench/org.eclipse.gemoc.example.k3fsm.model_examples.Bitshifting/.launch/EventK3FSM - Bitshifting(0110101).launch, official_samples/K3FSM/modeling_workbench/org.eclipse.gemoc.example.k3fsm.model_examples.Bitshifting/representations.aird, official_samples/K3FSM/modeling_workbench/org.eclipse.gemoc.example.k3fsm.model_examples.EdgeDetector/representations.aird, official_samples/K3FSM/modeling_workbench/org.eclipse.gemoc.example.k3fsm.model_examples.StringtoLowercase/representations.aird, official_samples/K3FSM/modeling_workbench/org.eclipse.gemoc.example.k3fsm.model_examples.StringtoUpperCase/representations.aird, official_samples/K3FSM/modeling_workbench/org.eclipse.gemoc.example.k3fsm.model_examples.ThreeStates/representations.aird, official_samples/K3FSM/modeling_workbench/org.eclipse.gemoc.example.k3fsm.model_examples.TrafficLight/representations.aird, official_samples/K3FSM/modeling_workbench/org.eclipse.gemoc.example.k3fsm.model_examples.TwoStates/.launch/EventK3FSM - TwoStates(abababa).launch, official_samples/K3FSM/modeling_workbench/org.eclipse.gemoc.example.k3fsm.model_examples.TwoStates/.launch/K3FSM- TwoStates(abababa).launch, official_samples/K3FSM/modeling_workbench/org.eclipse.gemoc.example.k3fsm.model_examples.TwoStates/representations.aird
Bump melange and update target platform to latest artefacts
Closes #304
=> Bump melange

gemoc_studio/plugins/gemoc_studio-eclipse-bom/pom.xml, gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.updatesite/gemoc_studio.product
deploys latest version of K3
make valid update site for tpd  available in the predefined update site
=> K3 update and tpd predefined update site

gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.branding/.classpath, gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.branding/.settings/org.eclipse.jdt.core.prefs, gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.branding/META-INF/MANIFEST.MF, gemoc_studio/plugins/org.eclipse.gemoc.language_workbench.documentation/.classpath, gemoc_studio/plugins/org.eclipse.gemoc.language_workbench.documentation/.settings/org.eclipse.jdt.core.prefs, gemoc_studio/plugins/org.eclipse.gemoc.language_workbench.documentation/META-INF/MANIFEST.MF, gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.targetplatform/gemoc_studio.target
Update targetplatform to use current version of ajdt
also enforce java17 in several plugins
=> Update ajdt in targetplatform

gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.updatesite/gemoc_studio.product
adapt start level to the commonly adopted values
=> adapt startlevel

gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.branding/plugin_customization.ini
This PR set the eclipse to be more similar to classic Eclipse package so when opening a file with an unknown extension it will ask to look into the eclipse market place.
This actually sets product preference to "ask marketplace" by default (can be changed by the user in the preferences later)
closes https://github.com/eclipse/gemoc-studio/issues/241
=> Ask marketplace of unknown file exension
