eclipse/gemoc-studio

- Jenkinsfile
- pom.xml
I propose to use this Jenkinsfile to drive the ci in a "multibranch pipeline job". (see the result in https://ci.eclipse.org/gemoc/job/gemoc-studio/ )
It enables the possibility to build studio on several branches (automatically detected) and be able to test them before accepting them.
It uses _resolveScm_ in order to use branches with the same name or fall back on master branch. Ie. you can have some change in 2 repo, they will be considered together if they are in branches with the same name.
One of the drawback of pipeline is that the workspace browser is a bit less easy to find in the CI UI. You need to select a branch, then the build, then the pipeline step, the node, then the workspace :disappointed_relieved:  (see [where did workspace go in …
> Jenkins multibranch pipeline support

- Jenkinsfile
- commons/plugins/org.eclipse.gemoc.commons.eclipse.messagingsystem.api/src/main/java/org/eclipse/gemoc/commons/eclipse/messagingsystem/api/MessagingSystemManager.java
- gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.branding/plugin.properties
- gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.branding/pom.xml
- gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.branding/src/main/filtered-resources/about.mappings
This PR adds description strings in the splash screen and in the about box in order to help identify the running studio. 
Ie. It indicates if this is an official version from eclipse CI on its master branch or on another branch or from an external CI (for example the old CI used before the code was pushed to Eclipse foundation)
> Studio variant identification

- commons/plugins/org.eclipse.gemoc.commons.eclipse.pde/src/org/eclipse/gemoc/commons/eclipse/pde/wizards/pages/pde/ui/templates/OptionTemplateSection.java
- commons/plugins/org.eclipse.gemoc.commons.eclipse.pde/src/org/eclipse/gemoc/commons/eclipse/pde/wizards/pages/pde/ui/templates/StringOption.java
This PR brings several improvement to the GEMOC project wizard templates.
in the main repo, it adds a fix about initial values not shown in the templates
this PR can be tested by looking at the CI https://ci.eclipse.org/gemoc/job/gemoc-studio/job/improve-gemoc-project-template-wizard/
> fixes the setValue of StringOption which failed to correctly display

- commons/plugins/org.eclipse.gemoc.commons.eclipse.messagingsystem.api/src/main/java/org/eclipse/gemoc/commons/eclipse/messagingsystem/api/MessagingSystem.java
- commons/plugins/org.eclipse.gemoc.commons.eclipse.messagingsystem.api/src/main/java/org/eclipse/gemoc/commons/messagingsystem/api/impl/StdioSimpleMessagingSystem.java
- commons/plugins/org.eclipse.gemoc.commons.eclipse.messagingsystem.ui/src/main/java/org/eclipse/gemoc/commons/eclipse/messagingsystem/ui/ConsoleLogLevel.java
- commons/plugins/org.eclipse.gemoc.commons.eclipse.messagingsystem.ui/src/main/java/org/eclipse/gemoc/commons/eclipse/messagingsystem/ui/EclipseMessagingSystem.java
- commons/plugins/org.eclipse.gemoc.commons.eclipse.messagingsystem.ui/src/main/java/org/eclipse/gemoc/commons/eclipse/messagingsystem/ui/internal/console/ConsoleIO.java
- commons/plugins/org.eclipse.gemoc.commons.eclipse.messagingsystem.ui/src/main/java/org/eclipse/gemoc/commons/eclipse/messagingsystem/ui/internal/console/EclipseConsoleIO.java
- commons/plugins/org.eclipse.gemoc.commons.eclipse.messagingsystem.ui/src/main/java/org/eclipse/gemoc/commons/eclipse/messagingsystem/ui/internal/console/message/ConsoleMessage.java
- commons/plugins/org.eclipse.gemoc.commons.eclipse.messagingsystem.ui/src/main/java/org/eclipse/gemoc/commons/eclipse/messagingsystem/ui/internal/console/message/DebugErrorMessage.java
- commons/plugins/org.eclipse.gemoc.commons.eclipse.messagingsystem.ui/src/main/java/org/eclipse/gemoc/commons/eclipse/messagingsystem/ui/internal/console/message/DebugMessage.java
- commons/plugins/org.eclipse.gemoc.commons.eclipse.messagingsystem.ui/src/main/java/org/eclipse/gemoc/commons/eclipse/messagingsystem/ui/internal/console/message/ErrorMessage.java
- commons/plugins/org.eclipse.gemoc.commons.eclipse.messagingsystem.ui/src/main/java/org/eclipse/gemoc/commons/eclipse/messagingsystem/ui/internal/console/message/ImportantMessage.java
- commons/plugins/org.eclipse.gemoc.commons.eclipse.messagingsystem.ui/src/main/java/org/eclipse/gemoc/commons/eclipse/messagingsystem/ui/internal/console/message/InfoMessage.java
- commons/plugins/org.eclipse.gemoc.commons.eclipse.messagingsystem.ui/src/main/java/org/eclipse/gemoc/commons/eclipse/messagingsystem/ui/internal/console/message/WarningMessage.java
Improve usability of the Messaging system
- add a new level for user messages : important. It allows to highlight the most important messages. In the eclipse console it displays using a blue bold font.
- only dev error and warning go to the Eclipse Error log view, user error and warning go only to the console
> Improve messagingsystem usability

- gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.branding/META-INF/MANIFEST.MF
- gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.branding/src/main/java/org/eclipse/gemoc/gemoc_studio/branding/discovery/wizards/DiscoveryWizard.java
- gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.branding/src/main/java/org/eclipse/gemoc/gemoc_studio/branding/discovery/wizards/DiscoveryWizardMainPage.java
- gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.branding/src/main/java/org/eclipse/gemoc/gemoc_studio/branding/discovery/wizards/Installer.java
- gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.branding/src/main/java/org/eclipse/gemoc/gemoc_studio/branding/discovery/wizards/Messages.java
- gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.branding/src/main/java/org/eclipse/gemoc/gemoc_studio/branding/discovery/wizards/PrepareInstallProfileJob.java
- gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.branding/src/main/java/org/eclipse/gemoc/gemoc_studio/branding/discovery/wizards/messages.properties
- gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.branding/src/main/java/org/eclipse/gemoc/gemoc_studio/branding/handlers/GemocPackageDiscovery.java
fixes https://github.com/eclipse/gemoc-studio/issues/52
This allows to have a better error reporting in case of installation failure via the discovery.
Due to API restriction, the code is not very nice and duplicates some classes from amalgam.
However a better fix has been provided directly in amalgam (https://git.eclipse.org/r/#/c/118366/ and https://bugs.eclipse.org/bugs/show_bug.cgi?id=531789 )
So this PR will have to be reverted as soon as the gerrit patch has been accepted and deployed in the official eclipse update site.
> Improve discovery

- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system/src/org/eclipse/gemoc/studio/tests/system/lwb/feature/XDSMLPerspective_Test.xtend
The SWTBot test `test02_toolbarDropDownNewMenuContent` was failing due to an error message appearing because a webkitgtk lib is not installed on the Eclipse CI slave.
This PR simply adds an SWTBot action to discard this error message if it appears, which allows the test to continue and pass.
CI build here (still building at the time of writing) : https://ci.eclipse.org/gemoc/job/gemoc-studio/job/workaround-problem-test-webkitgtk/
Signed-off-by: Erwan Bousse <erwan.bousse@tuwien.ac.at>
> [tests] Workaround to discard webkitgtk error message

- .grenrc.yml
- CHANGELOG.md
Use GREN (https://github.com/github-tools/github-release-notes) for generating release notes.
We use Pull Requests as input.
This implies that:
- we must tag every pull request in order to include it in the note
- we must follow some convention for the title of the pull request (see https://github.com/github-tools/github-release-notes)
1.  Start the subject line with a verb (e.g. Change header styles)
1.   Use the imperative mood in the subject line (e.g. Fix, not Fixed or Fixes header styles)
1.  Limit the subject line to about 50 characters
1.  Do not end the subject line with a period
1.  Separate subject from body with a blank line
1.  Wrap the body at 72 characters
1.  Use the body to explain what and why not how
Currently, the command has to be launched manually by one of the …
> Use Gren for release note management

- pom.xml
It includes https://github.com/diverse-project/melange/pull/114 in order
to better manage generated languages project as Gemoc projects since the project that hosts the .melange file is not supposed to be a Gemoc project.
This PR comes with https://github.com/eclipse/gemoc-studio-modeldebugging/pull/37
> Upgrade Melange to version 2018-04-11

- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.additions.feature/feature.xml
In order to remove these old connectors, the following features have
been split and reproduced locally instead of simply reusing them:
org.eclipse.sdk and org.eclipse.emf.diffmerge.sdk.feature
This saves about 7MB to the studio.
> Remove old scm connectors SVN and CVS from studio

- docs/org.eclipse.gemoc.studio.doc/src/main/asciidoc/dev/ContributingDocumentation.asciidoc
- docs/org.eclipse.gemoc.studio.doc/src/main/asciidoc/introduction_headContent.asciidoc
- gemoc_studio/plugins/org.eclipse.gemoc.language_workbench.documentation/plugin.xml
- gemoc_studio/plugins/org.eclipse.gemoc.language_workbench.documentation/toc.xml
Fixes eclipse help navigation table of content
also improve some information about how to build the documentation
fixes https://github.com/eclipse/gemoc-studio/issues/86
> Fixes eclipse help navigation table of content

- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.mwb/src/org/eclipse/gemoc/studio/tests/system/mwb/userstory/DebugOfficialExampleK3FSM_Test.xtend
- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.mwb/src/org/eclipse/gemoc/studio/tests/system/mwb/userstory/DeployOfficialExampleK3FSM_Test.xtend
add a base test for modeldebugging bug 66
https://github.com/eclipse/gemoc-studio-modeldebugging/issues/66
Currently skipped, must be enabled and improved (for example better detection of execution end) when fixed
> add a base test for modeldebugging bug #66

- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.additions.feature/feature.xml
- pom.xml
As the code submitted to Ecoretools project is very long to be accepted by its commiter team (https://bugs.eclipse.org/bugs/show_bug.cgi?id=537295),
this PR deploys a pre-release version of EPackage registration.
This version has been compiled from https://github.com/diverse-project/tools and deployed to http://www.kermeta.org/diverse-commons/updates/latest/
(sources are the same as the
one proposed to https://bugs.eclipse.org/bugs/show_bug.cgi?id=537295 )
This PR contributes to https://github.com/eclipse/gemoc-studio/issues/14
> Add pre-release version of ecoretools epackage registration

- dev_support/full_compilation/README.asciidoc
- dev_support/full_compilation/docker/entrypoint.sh
Changes working directory in order to correctly enable pomless builds
fixes https://github.com/eclipse/gemoc-studio/issues/133
small improvement in the documentation about how to use the docker image
> Fix docker file for pomless builds

- gemoc_studio/pom.xml
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.headless.product/src/main/filtered-resources/products/index.html
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.product/src/main/filtered-resources/products/index.html
- pom.xml
Nowadays, 32-bit versions of the studio are rarely used.
This PR remove these versions from the default distribution.
This saves some build time and disk space on the CI
(fixes https://github.com/eclipse/gemoc-studio/issues/114)
> Remove 32 bit versions of the studio

- Jenkinsfile
- README.md
- dev_support/full_compilation/pom.xml
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.branding.feature/feature.xml
- pom.xml
This PR adds the build support and deployment of the concurrent engine in the studio.
cf. https://github.com/eclipse/gemoc-studio/issues/146
It comes with several PR in other repositories:
* https://github.com/eclipse/gemoc-studio-moccml/pull/1
* https://github.com/eclipse/gemoc-studio-execution-moccml/pull/1
* https://github.com/eclipse/gemoc-studio-execution-ale/pull/8
* https://github.com/eclipse/gemoc-studio-modeldebugging/pull/98
> Add concurrent engine to studio

- docs/org.eclipse.gemoc.studio.doc/pom.xml
This PR re-enables the plantuml image generation.
Additionally, it provides a new profile (`plantuml`) that one can deactivate in order to speed up his build. (using the option `-P !plantuml`)
A message is shown in the log in order to remind this option. 
This message is shown as a warning if it detects a version 2.39 or 2.40 of Graphviz
> Re-enable plantuml figures in documentation

- gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.branding/src/main/java/org/eclipse/gemoc/gemoc_studio/branding/handlers/GemocPackageDiscovery.java
I've created a new URL on GEMOC site for discovery that is unique for the Studio 3.1.x (ie. current master and next official release this summer)
The url is http://gemoc.org/discovery/gemoc_3.1.x/catalog.xmi
Its content is also available on the following web page : http://gemoc.org/discovery/gemoc_3.1.x/catalog.html
Note : the goal is to make sure that all the content provided will remain stable (ie. contain update site specific to this version (no "lastest build" that may fail in the future)
contributes to https://github.com/eclipse/gemoc-studio/issues/120
> Use url for discovery that is unique for gemoc 3.1.x

- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.lwb/src/org/eclipse/gemoc/studio/tests/system/lwb/feature/XDSMLPerspective_Test.xtend
Removes some flaky test situations
contributes to https://github.com/eclipse/gemoc-studio/issues/123
> Do not wait for discovery update site availability check in tests

- gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.branding/META-INF/MANIFEST.MF
- gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.branding/pom.xml
- gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.headless/META-INF/MANIFEST.MF
- gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.headless/pom.xml
- gemoc_studio/plugins/org.eclipse.gemoc.language_workbench.documentation/META-INF/MANIFEST.MF
- gemoc_studio/plugins/org.eclipse.gemoc.language_workbench.documentation/pom.xml
- gemoc_studio/pom.xml
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.additions.feature/feature.xml
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.additions.feature/pom.xml
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.branding.feature/feature.xml
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.branding.feature/pom.xml
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.headless.feature/feature.xml
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.headless.feature/pom.xml
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.headless.product/gemoc_studio_headless.product
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.headless.product/pom.xml
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.product/gemoc_studio.product
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.product/pom.xml
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.updatesite/category.xml
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.updatesite/pom.xml
- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.backlog/META-INF/MANIFEST.MF
- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.backlog/pom.xml
- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.lwb/META-INF/MANIFEST.MF
- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.lwb/pom.xml
- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.mwb/META-INF/MANIFEST.MF
- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.mwb/pom.xml
- official_samples/K3FSM/language_workbench/pom.xml
As the official GEMOC Studio 3.1.0 has been released, this PR increases the version of the GEMOC Studio product to 3.2.0.
This prepares the next milestone (that will move its Eclipse  base from Eclipse Photon.1 to Eclipse June 2019) and makes sure that every nightly build is clearly newer than the official 3.1.0.
> Bump GEMOC Studio to 3.2.0

- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.updatesite/category.xml
- pom.xml
This PR integrates the fix of https://github.com/gemoc/ale-lang/issues/38 . Ie. ALE Engine was not stopping the engine in case of unexpected execution error.
It bumps ALE version to the latest available and includes some additions in ALE GEMOC Engine.
This PR comes with the following PR: https://github.com/eclipse/gemoc-studio-execution-ale/pull/21
> Stop ALE engine on error

- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.headless.feature/feature.xml
This pull request removes the old event manager from the studio and goes with [this pull request](https://github.com/eclipse/gemoc-studio-modeldebugging/pull/119)
Signed-off-by: d-leroy <dorian.leroy@tuwien.ac.at>
> Remove event manager from feature.xml

- commons/plugins/org.eclipse.gemoc.commons.eclipse.jdt.autosrcfolder/META-INF/MANIFEST.MF
One line addition to the new autosrc feature to set the Java compliance to 1.8, otherwise this error can happen when opening the autosrc preference page while running the studio with java 1.8:
>Unable to create the selected preference page.
>org/eclipse/gemoc/commons/eclipse/jdt/autosrcfolder/ui/WorkbenchPreferencePage has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> autosrc: set java compliance to 1.8

- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.updatesite/category.xml
- pom.xml
This PR bump to latest ALE version and complements https://github.com/eclipse/gemoc-studio-execution-ale/pull/24
> Bump ALE to latest version

- dev_support/full_compilation/README.asciidoc
- dev_support/full_compilation/docker/Dockerfile
- dev_support/full_compilation/docker/docker-compose.yml
- dev_support/full_compilation/docker/scripts/build_gemoc.sh
- dev_support/full_compilation/docker/scripts/uid_entrypoint
This PR contributes a new docker image allowing to build the full studio including the UI tests.
- Running the `mvn verify`  command locally may lead to some issues: for example, the UI tests will interact with the user display and make them fail if the user continues to work on her computer while running the tests.
This docker image provides a script that launches an Xvfb x server that frees the user display.
Additionally, it makes sure to compile using a jdk8 and the correct version of plantuml (which is buggy on recent Linux distribution cf. https://forum.plantuml.net/5425/relation-long-with-graphviz-using-labels-relations-namespace)
The readme provides some instructions about how to use this image for various needs.
A ready-to-use version of this image is available on docker hub: …
> Improved docker image for local build

- commons/plugins/org.eclipse.gemoc.commons.eclipse.jdt/src/org/eclipse/gemoc/commons/eclipse/jdt/JavaProject.java
- commons/plugins/org.eclipse.gemoc.commons.eclipse/src/org/eclipse/gemoc/commons/eclipse/core/resources/IProjectUtils.java
- docs/org.eclipse.gemoc.studio.doc/src/main/asciidoc/userguide/lw_CreateGEMOCProject_headContent.asciidoc
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.headless.feature/feature.xml
- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.lwb/src/org/eclipse/gemoc/studio/tests/system/lwb/feature/XDSMLPerspective_Test.xtend
- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.lwb/src/org/eclipse/gemoc/studio/tests/system/lwb/userstory/CreateMelangeBasedSingleSequentialLanguageFromOfficialFSM_Test.xtend
- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.lwb/src/org/eclipse/gemoc/studio/tests/system/lwb/userstory/CreateSequentialLanguageFromOfficialK3FSM_Test.xtend
- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.lwb/src/org/eclipse/gemoc/studio/tests/system/lwb/userstory/CreateSingleSequentialLanguageFromOfficialFSM_Test.xtend
- official_samples/K3FSM/docs/K3FSM.asciidoc
- official_samples/K3FSM/language_workbench/org.eclipse.gemoc.example.k3fsm.xdsml/.project
- official_samples/K3FSM/language_workbench/org.eclipse.gemoc.example.k3fsm.xdsml/META-INF/MANIFEST.MF
- official_samples/K3FSM/language_workbench/org.eclipse.gemoc.example.k3fsm.xdsml/plugin.xml
- official_samples/MelangeK3FSM/language_workbench/org.eclipse.gemoc.example.melangek3fsm.fsm/META-INF/MANIFEST.MF
- official_samples/MelangeK3FSM/language_workbench/org.eclipse.gemoc.example.melangek3fsm.fsm/plugin.xml
- official_samples/MelangeK3FSM/language_workbench/org.eclipse.gemoc.example.melangek3fsm.xsfsm.xsfsm/plugin.xml
- official_samples/MelangeK3FSM/language_workbench/org.eclipse.gemoc.example.melangek3fsm.xsfsm/META-INF/MANIFEST.MF
Companion PR to https://github.com/eclipse/gemoc-studio-modeldebugging/pull/133
It adapts the examples to the removal of the `org.eclipse.gemoc.gemoc_language_workbench.sequential.xdsml` extension point
It adapts the release engineering to the removal of `org.eclipse.gemoc.execution.sequential.javaxdsml.api` plugin
> Use general extension point + nature and builder refactoring

- dev_support/jenkins/docker/Dockerfile
This PR contributes a new docker images that is based on https://github.com/eclipse-cbi/jiro/tree/master/jenkins-agent-images/migration-fat-agent
this migration-fat-agent is the image used when using 
```
agent   {  
kubernetes {
label 'migration'
}
}
``` 
in the jenkins file
This modified image allows to:
- remove some useless tool in the image
- add graphviz:  fix  https://github.com/eclipse/gemoc-studio/issues/151
- add ffmpeg and tmux (in order to try to capture video of the x display of tests)
the docker image is deployed https://hub.docker.com/repository/docker/gemoc/gemoc-jenkins-fat-agent in order to be used by the jenkinsfile (see https://github.com/gemoc/gemoc-studio-eclipse-integration )
> Use custom docker image for building the studio on the CI

- pom.xml
This PR bumps Sirius from 6.0.2 to 6.1.3
This is the companion PR of https://github.com/eclipse/gemoc-studio-modeldebugging/pull/138
> Bump to Sirius 6.1.3

- official_samples/K3FSM/language_workbench/org.eclipse.gemoc.example.k3fsm.xdsml/plugin.xml
Companion PR to https://github.com/eclipse/gemoc-studio-modeldebugging/pull/139
This PR fixes the xdsmlFilePath attribute in plugin.xml of the examples
contributes to
https://github.com/eclipse/gemoc-studio-modeldebugging/issues/137
> Fix xdsmlFilePath attribute in plugin.xml

- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.mwb/src/org/eclipse/gemoc/studio/tests/system/mwb/userstory/DebugOfficialExampleK3FSM_Test.xtend
This PR improves resilience against flaky tests in the debugger test suites (cf. https://github.com/eclipse/gemoc-studio/issues/123)
It improves 2 cases:
- it uses https://github.com/eclipse/gemoc-studio-modeldebugging/pull/143 in order to better detect the effect of the click on F5  (Step Into) and make sure that it was handled before continuing
- it makes sure to wait for the expansion of the TreeItem before looking for an element (apparently swtBot doesn't do it natively)
> Add wait for treeitem after expand in tests

- dev_support/full_compilation/pom.xml
- docs/org.eclipse.gemoc.studio.doc/pom.xml
- docs/org.eclipse.gemoc.studio.doc/src/main/asciidoc/master.asciidoc
Companion PR to https://github.com/eclipse/gemoc-studio-modeldebugging/pull/147
This PR adapts the build scripts and updates the documentation link to the new git repository https://github.com/eclipse/gemoc-studio-execution-java/ .
Contributes to https://github.com/eclipse/gemoc-studio-modeldebugging/issues/78
> Move JavaEngine to its own dedicated git repository

- dev_support/full_compilation/pom.xml
- docs/org.eclipse.gemoc.studio.doc/pom.xml
- pom.xml
This PR add some DistributionManagement information allowing to deploy GEMOC artefact in a standard maven repository (ie. not P2)  so we can create dependencies to the jars using the maven style in pure java application.
This PR selects a set of jars to be deployed (by using the `<maven.deploy.skip>true</maven.deploy.skip>` property)
The CI currently deploys to https://repo.eclipse.org/content/groups/gemoc/
To use the artefacts, simply add the following in your pom.xml (or equivalent in graddle files)
```
<repositories>
<repository>
<id>nexus-eclipse-gemoc</id>
<name>Nexus Eclipse GEMOC</name>
<releases><enabled>true</enabled></releases>
<snapshots><enabled>true</enabled></snapshots>
<url>https://repo.eclipse.org/content/groups/gemoc/</url>
</repository>
</repositories>
```
then add as …
> Deploy GEMOC artefacts to maven repository (repo.eclipse.org)

- dev_support/jenkins/docker/Dockerfile
Yesterday, the CI suddenly failed when starting the UI tests due to empty /etc/machine-id error
> process 5465: D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text
See the manual page for dbus-uuidgen to correct this issue.
D-Bus not built with -rdynamic so unable to print a backtrace
This PR updates the docker image by copying
https://github.com/eclipse-cbi/jiro-agents/blob/a892e25179578ba4d99abc79524d1ecdbf25d4dd/centos-7/Dockerfile#L93 to create a machine-id in the docker image
> Fix machine-id of the jenkins docker image

- gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.headless/src/org/eclipse/gemoc/gemoc_studio/headless/runner/ALEInterpretedSequentialRunner.java
Remove use and registration  of ALESiriusInterpreter in headles launcher.
This ALESiriusInterpreter interpreter is used only to provide `ale:` queries in odesign.
This isn't required since the headless engine doesn't display any diagram.
Contribute to https://github.com/eclipse/gemoc-studio-execution-ale/issues/44 
https://github.com/eclipse/gemoc-studio-execution-ale/pull/45
> Remove use of ALESiriusInterpreter in headles launcher

- gemoc_studio/pom.xml
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.additions.feature/feature.xml
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.updatesite/category.xml
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.updatesite/gemoc_studio.product
- official_samples/K3FSM/language_workbench/pom.xml
- official_samples/sample.deployers/pom.xml
- pom.xml
This PR adds the ELK experimental support for Sirius. It provides better autolayout for Sirius diagram.
It also 
- cleans up some of the P2 repositories used while building
- remove some old repositories in the list of update sites presented in "Available update site" of the studio 
ELK -> 0.7.1
Sirius ELK support
AJDT 4.10
remove nebula update site
Closes https://github.com/eclipse/gemoc-studio/issues/221
- https://github.com/eclipse/gemoc-studio-modeldebugging/pull/184
- https://github.com/eclipse/gemoc-studio-execution-java/pull/15
- https://github.com/eclipse/gemoc-studio-execution-moccml/pull/50
- https://github.com/eclipse/gemoc-studio-moccml/pull/18
> Add Sirius ELK support

- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.mwb/src/org/eclipse/gemoc/studio/tests/system/mwb/userstory/DebugOfficialExampleK3FSM_Test.xtend
Makes a tiny change to a test case in order to take into account the new label of stack frames when debugging models. This new label is due to changes made to the GEMOC execution framework to introduce the management of parameters in execution steps.
In `DebugOfficialExampleK3FSM_Test`, replace 
```FSM] TwoStateUpcast#initializeModel()``` 
by 
```FSM] TwoStateUpcast#initializeModel([])```
None
- https://github.com/eclipse/gemoc-studio-modeldebugging/pull/186
- https://github.com/eclipse/gemoc-studio-modeldebugging/pull/187
> [Event Manager] Update MW test case for small change in model stack trace

- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.mwb/src/org/eclipse/gemoc/studio/tests/system/mwb/userstory/DebugOfficialExampleK3FSM_Test.xtend
- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.mwb/src/org/eclipse/gemoc/studio/tests/system/mwb/userstory/DeployOfficialExampleK3FSM_Test.xtend
- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.mwb/src/org/eclipse/gemoc/studio/tests/system/mwb/userstory/DeployOfficialExampleK3MelangeFSM_Test.xtend
This PR improves the tests
- Improvement of the log of the SWT widget in order to analyze them
- replace the use of SWTbot by direct programming of the close and dispose engine
-
Contribute to https://github.com/eclipse/gemoc-studio/issues/123
Flaky tests are not really fixed, we only use direct programming instead of using SWTBot (apparently the Engine view doesn't display its buttons in some situations)
- PR https://github.com/eclipse/gemoc-studio-modeldebugging/pull/192
> Disable flacky tests

- gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.branding/pom.xml
Use image-tools-plugin v0.1.0 that has been recently moved from diverse-team to gemoc organisation (and published on maven central)
This plugin offers maven plugin to produce the bmp image required by eclipse as a splash screen
> Use image-tools-plugin 0.1.0 from GEMOC organization

- dev_support/jenkins/docker/Dockerfile
- dev_support/jenkins/docker/README.asciidoc
Improve the docker image in order to be able to use it locally (ie. not in the Kubernetes context of Eclipse Jenkins)
Add some tools directly to the image. In Jenkins, java and maven are installed by the Jenkins agent. In order to use this image without the Jenkins agent context, we need to install these tools directly in the image.
- use java 11 as the default alternative 
- install maven
- add some instructions about building locally using this image in a way that is similar to Jenkins  (ie. basic mvn commands, connection to vnc using a vncclient, ...)
> Improve docker for CI

- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.updatesite/gemoc_studio.product
In recent GEMOC Studio package (3.3.0),  Eclipse isn't prompting anymore for the workspace location on startup.
This PR re-enable this prompt.
add `-Dosgi.dataAreaRequiresExplicitInit=true` in the GemocStudio.ini
Fixes https://github.com/eclipse/gemoc-studio/issues/237
> re-enable workspace location prompt on startup

- dev_support/launchconf/gemoc-studio pomfirst_full_compilation.launch
- dev_support/pomfirst_full_compilation/pom.xml
- gemoc_studio/pomfirst/gemoc-studio-bom/pom.xml
- gemoc_studio/pomfirst/pom.xml
- gemoc_studio/pomfirst/thirdparty-bundle/org.eclipse.debug.core/pom.xml
- gemoc_studio/pomfirst/thirdparty-bundle/org.eclipse.debug.ui/pom.xml
- gemoc_studio/pomfirst/thirdparty-bundle/org.eclipse.emf.compare/pom.xml
- gemoc_studio/pomfirst/thirdparty-bundle/org.eclipse.emf.edit/pom.xml
- gemoc_studio/pomfirst/thirdparty-bundle/org.eclipse.emf.transaction/pom.xml
- gemoc_studio/pomfirst/thirdparty-bundle/pom.xml
Fixes deployment to nexus issue
version of thirdparty jar now use a snapshot version instead of a release version (because the nexus doesn't allow to re-deploy already released jars, thus preventing continuous integration on possibly updated pom.xm metadata for the given jar)
add some metadata (url, developer, scm distribution) in prevision of deployment on maven central.
> Fix mvn deploy config

- gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.headless/META-INF/MANIFEST.MF
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.headless.feature/feature.xml
Enable use of the GEMOC Update site for recent Eclipse package (Ie. eclipse package newer than the version used to compile the studio/updatesite)
replace included plugins by dependency plugins
Contributes to https://github.com/eclipse/gemoc-studio/issues/248
- PR https://github.com/eclipse/gemoc-studio-moccml/pull/21
> Fixes usage of GEMOC updatesite with recent Eclipse package

- .mvn/extensions.xml
- gemoc_studio/plugins/gemoc_studio-eclipse-bom/pom.xml
- gemoc_studio/plugins/org.eclipse.gemoc.gemoc_studio.branding/pom.xml
- gemoc_studio/pomfirst/gemoc-studio-bom/pom.xml
Bump Eclipse base IDE to 2021-12
use corresponding tycho (2.5.0) and xtend/xtext (2.25.0)
- https://github.com/eclipse/gemoc-studio-modeldebugging/pull/213
- https://github.com/eclipse/gemoc-studio-execution-java/pull/23
- https://github.com/eclipse/gemoc-studio-execution-ale/pull/52
- https://github.com/eclipse/gemoc-studio-moccml/pull/23
- https://github.com/eclipse/gemoc-studio-execution-moccml/pull/65
> Bump eclipse 2021 12

- gemoc_studio/pom.xml
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.additions.feature/feature.xml
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.targetplatform/.project
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.targetplatform/.settings/org.eclipse.core.resources.prefs
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.targetplatform/README.md
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.targetplatform/gemoc_studio.target
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.targetplatform/gemoc_studio.tpd
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.targetplatform/pom.xml
- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.lwb/pom.xml
- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.mwb/pom.xml
- official_samples/K3FSM/language_workbench/pom.xml
- official_samples/sample.deployers/pom.xml
- pom.xml
This PR changes the way the external update sites are imported in the build.
Instead of using maven repository like:
```
<repositories>
<repository>
<id>Eclipse release</id>
<layout>p2</layout>
<url>${eclipse.release.p2.url}</url>
</repository>
```
It uses a tpd description file in order to generate a targetplatform file.
This tpd allows to not specify precisely the version of the imported unit while helping to control where they come from.
A readme file explains how to update the target file from the tpd (in `gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.targetplatform`)
NOTE: the use of the tpd is partial: the K3 and melange updatesite currently cannot be integrated in the target because these tools depends on gemoc.dsl that is actually build by GEMOC. This creates a kind of cycle …
> Use tpd for defining target platform

- dev_support/jenkins/docker/Dockerfile
- add webkitgtk4
- build with updated centos7
- use javafx17
- add xdg-utils
> Update docker ci eclipse jenkins image

- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.targetplatform/.gitignore
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.targetplatform/README.md
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.targetplatform/gemoc_studio.target
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.targetplatform/update_target.sh
Update the `gemoc_studio.target` to latest versions availble on internet
Add a script able to automate the generation of the `gemoc_studio.target`  from `gemoc_studio.tpd`
An update of the `jenkinsfile` is required to fully take advantage of this script. (in https://github.com/gemoc/gemoc-studio-eclipse-integration and https://github.com/gemoc/gemoc-studio-eclipseforks-integration)
Closes https://github.com/eclipse/gemoc-studio/issues/262
> Update target to latest and target generation script

- .mvn/extensions.xml
- dev_support/pomfirst_full_compilation/README.asciidoc
- dev_support/tycho_full_compilation/README.asciidoc
- docs/org.eclipse.gemoc.studio.doc/pom.xml
- docs/org.eclipse.gemoc.studio.doc/src/main/asciidoc/dev/Protocols_headContent.asciidoc
- docs/org.eclipse.gemoc.studio.doc/src/main/asciidoc/images/dev/ProtocolsOverview.plantuml
- docs/org.eclipse.gemoc.studio.doc/src/main/asciidoc/master.asciidoc
- gemoc_studio/plugins/gemoc_studio-eclipse-bom/pom.xml
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.headless.feature/feature.xml
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.targetplatform/gemoc_studio.target
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.targetplatform/gemoc_studio.tpd
- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.targetplatform/gemoc_studio_dev.target
- Add a new IEngineAddon  that implements the IEngineAddon api as a web protocol. (`org.eclipse.gemoc.executionframework.addon.eaop.server`)
- Add a new Websocket server plugin allowing to easily offer websocket endpoint from Eclipse. (`org.eclipse.gemoc.ws.server` and `org.eclipse.gemoc.commons.utils`)
- Add an JSONSchema to protocol generator. (`protocols/generators/ts/JSONSchema2APIProtocolGenerator`) it is able to generate java API, Typescript API, plantuml description from the schema.
- Add EAOP (Engine AddOn Protocol) definition and generated Java and TS API, (`protocols/engine_addon_protocol`)
- Updated documentation with content generated from the protocols
- Bump tycho to 2.7.0
- Add Jetty 10 in the studio (directly from maven central as there is no update site providing it)
- …
> Initial version of a Webprotocol based EngineAddon server

- dev_support/jenkins/docker/Dockerfile
Add nodejs to the docker image used by https://ci.eclipse.org/gemoc/job/gemoc-studio-integration/
This image is currently deployed as `gemoc/gemoc-jenkins-fat-agent:2022-04-26` on docker.io
Contribute to https://github.com/eclipse/gemoc-studio/pull/264
> Add nodejs to docker for CI

- official_samples/K3FSM/language_workbench/org.eclipse.gemoc.example.k3fsm.k3dsa/src/org/eclipse/gemoc/example/k3fsm/k3dsa/k3fsmAspects.xtend
Currently, the semantics of K3FSM can only execute models where all transitions have both an input and an output string.
This PR solves that, and will make sure the semantics can legally fire a transition that has no input string.
- Add new condition to consider a transition to be "valid" : `t.input === null`
- Adapt code to the fact that `input` and `output` may be `null`
- Reformat k3fsm semantics file
> Make K3FSM semantics work with null input/outputs

- gemoc_studio/pomfirst/gemoc-studio-bom/pom.xml
Add support for pomfirst version of `org.eclipse.gemoc.commons.eclipse.pde`
- https://github.com/eclipse/gemoc-studio-commons/pull/1
- https://github.com/eclipse/gemoc-studio/pull/276
- https://github.com/eclipse/gemoc-studio-modeldebugging/pull/224
- https://github.com/eclipse/gemoc-studio-execution-java/pull/28
- https://github.com/eclipse/gemoc-studio-execution-moccml/pull/70
> Split commons eclipse pde to remove UI dependency

- gemoc_studio/plugins/gemoc_studio-eclipse-bom/pom.xml
- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.lwb/src/org/eclipse/gemoc/studio/tests/system/lwb/feature/GenerateLangRuntime4OfficialExampleMelangeK3FSM_Test.xtend
- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.lwb/src/org/eclipse/gemoc/studio/tests/system/lwb/userstory/CreateMelangeBasedSingleSequentialLanguageFromOfficialFSM_Test.xtend
use a fixed version of K3 instead of the _latest_   version that may change overtime and create reproducibility issues
use current K3 version  (update_2022-09-08)
This will prepare work for validating 
- https://github.com/eclipse/gemoc-studio-execution-java/pull/29
- https://github.com/eclipse/gemoc-studio-execution-ale/pull/57
- https://github.com/eclipse/gemoc-studio-execution-moccml/pull/73
- https://github.com/eclipse/gemoc-studio-modeldebugging/pull/226
when https://github.com/diverse-project/k3/pull/87 will be deployed
> Use fixed version of k3 to ensure reproducibility

- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.mwb/src/org/eclipse/gemoc/studio/tests/system/mwb/userstory/DebugOfficialExampleK3FSM_Test.xtend
In MW UI test cases, we explicitly check for a string with the complete signature of an execution trace in the stack trace.
(This is indirectly the reason for this failing test result: https://ci.eclipse.org/gemoc/job/gemoc-studio-integration/job/stepReturn/10/testReport/)
Until now, such parameters were not correctly provided to step objects, and thus not displayed. This changes with this other PR: https://github.com/eclipse/gemoc-studio-modeldebugging/pull/227
The current PR adapts the MW test case to expect the step parameter to be displayed, as we should have expected in the first place.
(Warning: I forgot to give the same name to both branches)
- PR https://github.com/eclipse/gemoc-studio-modeldebugging/pull/227
> Manage step params in MW test cases

- gemoc_studio/plugins/gemoc_studio-eclipse-bom/pom.xml
Required to fix the `master` branch (see https://ci.eclipse.org/gemoc/job/gemoc-studio-integration/job/master/448/)
> Bump K3 version to 2022-12-20

- gemoc_studio/plugins/gemoc_studio-eclipse-bom/pom.xml
align xtend to 2.27.0 available in eclipse 2022-06 
use latest version of k3 (2023-01-09)
> Bump xtend and k3

- gemoc_studio/plugins/gemoc_studio-eclipse-bom/pom.xml
- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.lwb/src/org/eclipse/gemoc/studio/tests/system/lwb/userstory/CreateMelangeBasedSingleSequentialLanguageFromOfficialFSM_Test.xtend
- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.lwb/src/org/eclipse/gemoc/studio/tests/system/lwb/userstory/CreateSequentialLanguageFromOfficialK3FSM_Test.xtend
- gemoc_studio/tests/org.eclipse.gemoc.studio.tests.system.lwb/src/org/eclipse/gemoc/studio/tests/system/lwb/userstory/CreateSingleSequentialLanguageFromOfficialFSM_Test.xtend
- Add some debug info in test about shell
- try to force cancel job "Open Blocked Dialog" as an attempt to avoid failure
- disable Sirius project creation in Language Worbench user story test as they are flaky too often
- bump K3 to latest version 2023-02-24
Contribute to https://github.com/eclipse/gemoc-studio/issues/123
- https://github.com/eclipse/gemoc-studio-modeldebugging/pull/228
> Flaky test management

- gemoc_studio/plugins/gemoc_studio-eclipse-bom/pom.xml
Bump to the latest version of K3 that includes the support for all kind of StepCommand (ie. result being  void, null or an object)
- https://github.com/eclipse/gemoc-studio-modeldebugging/pull/229
- https://github.com/eclipse/gemoc-studio-execution-ale/pull/59
- https://github.com/eclipse/gemoc-studio-execution-java/pull/30
- https://github.com/eclipse/gemoc-studio-execution-moccml/pull/74
> Bump to version of k3 including StepCommand return null fix

- dev_support/jenkins/docker/Dockerfile
With Eclipse CI infrastructure update, our build was failing.
The docker image needed an upgrade of the Jenkins agent
This PR refactored the docker image to clearly use the base image from Eclipse CBI instead of trying to rebuild completely our images by ourselves.
the image is published on docker.io in https://hub.docker.com/repository/docker/gemoc/gemoc-jenkins-fat-agent/general 
In the process, several components have been upgraded :
- CentOS 8 (instead of 7)
- NodeJS 20 (instead of 17)
> Jenkins docker update

- gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.updatesite/src/main/filtered-resources/products/index.html
Fixes the download page for the current nightly build
With the new Eclipse version 2023-06 (see    #299  ) Linux and macos versions are distributed as tag.gz instead of zip 
This PR adapts the download page index https://download.eclipse.org/gemoc/packages/nightly/ to correctly point to these artefacts.
> fix download page of nightly build

- .project
- dev_support/gemoc_builder/README.asciidoc
- dev_support/gemoc_builder/docker/Dockerfile
- dev_support/gemoc_builder/docker/cache-m2/.gitignore
- dev_support/gemoc_builder/docker/log/.gitignore
- dev_support/gemoc_builder/docker/scripts/entrypoint
- dev_support/gemoc_builder/docker/scripts/generate_protocols.sh
- dev_support/gemoc_builder/docker/scripts/pomfirst_build.sh
- dev_support/gemoc_builder/docker/scripts/start-vnc.sh
- dev_support/gemoc_builder/docker/scripts/tycho_build.sh
- dev_support/jenkins/docker/Dockerfile
- dev_support/jenkins/docker/README.asciidoc
- dev_support/tycho_full_compilation/README.asciidoc
- dev_support/tycho_full_compilation/docker/Dockerfile
- dev_support/tycho_full_compilation/docker/docker-compose.yml
- dev_support/tycho_full_compilation/docker/entrypoint.sh
- dev_support/tycho_full_compilation/docker/log/.gitignore
- dev_support/tycho_full_compilation/docker/scripts/build_gemoc.sh
- dev_support/tycho_full_compilation/docker/scripts/entrypoint
- dev_support/tycho_full_compilation/docker/scripts/uid_entrypoint
Add a new docker image allowing to run the various build and test tasks locally.
It will also be used in an alternative CI (based on docker action and optionnaly with internally hosted runner so we may overcome the issue of the 4GB of ram proposed by the jenkins infrastructure
The image features:
- a VNC server allowing to connect/disconnect the display without interference with the developer PC (and thus help investigating the integration test issues )
- management of user id, so the files generated by the compilation can be mixed with the host PC (allow mapping of the uid:gid)
- build script for the common tasks (protocol generation, tycho build and test, pomfirt build)
- contains all required tooling, graphviz, nodejs, java 17, maven
- based on ubuntu 24.04 with display manager = sddm, …
> Adapt docker for local build

- dev_support/gemoc_builder/README.asciidoc
- dev_support/gemoc_builder/docker/scripts/tycho_build.sh
improve to options available for the different commands mainly for local use.
It also adds the possibility to display tycho resolver debug informations
restructure the tycho_build.sh option as follow:
- `tycho_build.sh` 
- Usage: `./tycho_build.sh [Options]* CommandName`
- CommandName:  `full clean | no_system_test | system_test_only | tycho_dependencies`
- `full` -> `mvn clean install` of all projects (includes system test)
- `clean` -> `mvn clean`
- `no_system_test` -> `mvn install` of the studio except the system test projects
- `system_test_only` -> `mvn verify` of the system test projects
- `tycho_dependencies` -> display the plugin dependencies computed by tycho
- Options: `[-b|--batch-mode] [-d|--debug] [-l|--linux] [-o|--offline] [-r|--debugResolver]`
- `batch-mode` -> removes …
> Improve tycho_build.sh to help local debug with the docker image
